### ISSUE TITLE
i need some guides plz

### ISSUE THREAD

**Issue by a469865520** [lingo3d/lingo3d#5]
hi,Author! 

I'm learning this,but the document is hard to understand.Can you share me a copy of the source code about "fairy-tale",plz?

send to e-mail 469865520@qq.com,thx!!!!!

**Comment by lingosandi** [comment]
I'll get all examples uploaded in the afternoon. Check back later.

**Comment by a469865520** [comment]
but how do I unbind my perspective from the camera when I'm using the 3rd person camera?Because I just want the camera to focus on me but don't want the character to follow the mouse control and rotate

**Comment by lingosandi** [comment]
CodeSandbox:
https://codesandbox.io/s/lingo3d-examples-react-fairytale-4b0wzv?file=/src/App.jsx

GitHub:
https://github.com/lingo3d/examples-react-fairytale

**Comment by lingosandi** [comment]
In your case, I'd use OrbitCamera. Lemme upload another example.

**Comment by lingosandi** [comment]
CodeSandbox:
https://codesandbox.io/s/lingo3d-examples-react-fairytale-idle-ul0zks?file=/src/App.jsx

**Comment by a469865520** [comment]
嘿，老兄！不过在第三人称视角下怎么用A或D控制其左右走路呢，我只能前后走。

**Comment by lingocode** [comment]
> 嘿，老兄！不过在第三人称视角下怎么用A或D控制其左右走路呢，我只能前后走。

hellohello 要不要加入我们的内测群？群里问 效率高:)

**Comment by lingosandi** [comment]
嗯嗯是的，我们有个内测群，现在文档和例子还在完善，群里问答效率高。晚点我给你个左右移动的例子。

**Comment by a469865520** [comment]
拉我

**Comment by a469865520** [comment]
可以私信469865520@qq.com
