### ISSUE TITLE
How to render text as 3D view?

### ISSUE THREAD

**Issue by FaiezWaseem** [lingo3d/lingo3d#6]
Hi i want to render text as 3D something like this
![Screenshot_20220328-172858](https://user-images.githubusercontent.com/78906502/160398199-e234461e-f24a-4dad-8c61-3315c3cb5fc0.jpg)
So like i when hardcode write my name it shows in 3d form like shown above

**Comment by lingosandi** [comment]
Hello, the easiest way is to use google-font-to-svg-path (https://danmarshall.github.io/google-font-to-svg-path/) to generate an svg path of your text. Make sure you check "Separate Characters" on that page. Then, download the SVG into your project's public folder, and load it using  "<SVGMesh src="text.svg" />". Here's an example: https://stackblitz.com/edit/vitejs-vite-e57mrk?file=src%2FApp.jsx&terminal=dev

**Comment by FaiezWaseem** [comment]
Hi , thanks for the response , its working Great thanku
